### ISSUE TITLE
How to use in modals

### ISSUE THREAD

**Issue by rdelriods01** [mezoistvan/ng2-flatpickr#1]
Hi mezoistvan,

I'm trying to use your code in my application, and it works well when I put it in any component view, but when I put inside a dialog it doesn't work, Am I missing something?  I'm using angular-material for dialogs. 

UPDATE..

I already know the problem... when I inspected the view with chrome, I realized that material-dialog creates a div with class="cdk-overlay-containe", with z-index=1000. The calendar view was behind this dialog, that's why I didn't see it.

**Comment by mezoistvan** [comment]
Hi!
Thanks for the remark. Flatpickr is able to append to different HTMLElements, not just the body. https://chmln.github.io/flatpickr/options/ Passing the config file as an @Input() should solve this issue. I will work on this shortly.
