### ISSUE TITLE
Request for a directive

### ISSUE THREAD

**Issue by dohpaz42** [mezoistvan/ng2-flatpickr#10]
It would be nice if this package could also be provided with a directive so that we can use our own markup and not just the markup of the component.

Thank you!

**Comment by dohpaz42** [comment]
I am going to attempt to write the directive, and then make a PR. One question I would like your help with is how do you go about compiling the project so that you get the js and js.map files?

**Comment by mezoistvan** [comment]
Thanks, that would be a huge help! :) I just run the prepublish script `npm run prepublish` or `tsc`. Then `npm publish` manually.
