### ISSUE TITLE
Production builds

### ISSUE THREAD

**Issue by rujorgensen** [mezoistvan/ng2-flatpickr#19]
Hi,

I just moved to the production phase on a large project and I am getting this error when building my project with the "--prod"-switch on. Like this: "ng build --prod".

"**ERROR in Unexpected value 'Ng2FlatpickrComponent in C:/Users/rj/Documents/Workspace/PROJECT_NAME/node_modules/ng2-flatpickr/src/ng2-flatpickr.component.d.ts' declared by the module 'AppModule in C:/Users/rj/Documents/Workspace/PROJECT_NAME/src/app/app.module.ts'. Please add a @Pipe/@Directive/@Component annotation.  ERROR in ./src/main.ts Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'C:\Users\rj\Documents\Workspace\PROJECT_NAMEI\src'  @ ./src/main.ts 3:0-74  @ multi ./src/main.ts**"

There seems to be a problem with the ng2-flatpickr library and the build is not successful. Before I investigate further and/or create a plunkr, I just want to ask if anyone else are having similar problems?

These are my dependencies:

```

 "dependencies": {
    "@agm/core": "^1.0.0-beta.0",
    "@amcharts/amcharts3-angular": "^1.2.1",
    "@angular/animations": "^4.2.5",
    "@angular/common": "^4.2.5",
    "@angular/compiler": "^4.2.5",
    "@angular/core": "^4.3.3",
    "@angular/forms": "^4.2.5",
    "@angular/http": "^4.2.5",
    "@angular/platform-browser": "^4.2.5",
    "@angular/platform-browser-dynamic": "^4.2.5",
    "@angular/platform-server": "^4.2.5",
    "@angular/router": "^4.2.5",
    "@reactivex/rxjs": "^5.4.2",
    "@types/lodash": "^4.14.68",
    "angular-font-awesome": "^2.0.2",
    "angular2-google-maps": "^0.17.0",
    "angular2-qrscanner": "^0.1.7",
    "chart.js": "^2.5.0",
    "core-js": "^2.4.1",
    "d3": "^4.9.1",
    "font-awesome": "^4.7.0",
    "lodash": "^4.17.4",
    "ng2-flatpickr": "^0.1.18",
    "ng2-nvd3": "^2.0.0-rc3",
    "ng2-toastr": "^4.1.2",
    "ng2-translate": "^5.0.0",
    "rxjs": "^5.1.0",
    "sprintf-js": "^1.1.1",
    "ts-helpers": "^1.1.2",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@angular/cli": "^1.2.0",
    "@angular/compiler-cli": "^4.2.5",
    "@types/jasmine": "^2.5.53",
    "@types/node": "^8.0.7",
    "angular-2-local-storage": "^1.0.1",
    "angular2-template-loader": "^0.6.2",
    "codelyzer": "3.1.2",
    "electron": "^1.6.11",
    "jasmine-core": "^2.7.0",
    "jasmine-spec-reporter": "^4.1.1",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-remap-istanbul": "^0.6.0",
    "protractor": "^5.1.2",
    "reflect-metadata": "^0.1.10",
    "rxjs": "^5.4.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.5.0",
    "typescript": "~2.3.3",
    "wallaby-webpack": "0.0.38"
  }
```

Thanks!

**Comment by indemi** [comment]
I have the same problem

**Comment by rujorgensen** [comment]
Hi Indemi,

Thanks for commenting. I switched to the ngx-flatpickr flatpickr wrapper and everything is fine now. Apologies to the author for abandoning this otherwise fine component, but I had a project that could not be delayed :).

Will unsubscribe.

**Comment by jcope** [comment]
Anyone able to make any progress on this item? It is syntax or structural? Ionic version# related?
 `@ionic/cli-utils  : 1.8.1
   ionic (Ionic CLI) : 3.8.1`

Could the problem be in the declaration of the component in ng2-flatpickr.component.d.js?
`    Ng2FlatpickrComponent = Ng2FlatpickrComponent_1 = __decorate([
    Component({
    selector: 'ng2-flatpickr',`
??

**Comment by jorge-indigo** [comment]
Any solution for this? I couldn't use ngx-flatpickr wrapper as @rujorgensen suggested because it fails too.

**Comment by jcope** [comment]
No, still haven't been able to do a production build with this ng2-flatpickr. My solution? Stop using production builds. Let me know if you come up with a better/appropriate solution!

**Comment by voznik** [comment]
looks like someone fixed this **annoying bug** in his fork: https://github.com/utahhealthcare/ng2-flatpickr/commit/22f80aa6bc40cc57a41b97cc8eaadf84fecdb912

**Comment by mezoistvan** [comment]
@voznik I think you meant #21 but hey, thats still solved!

**Comment by laurensvanpoucke** [comment]
Any updates on this one ?

**Comment by mezoistvan** [comment]
Version 1.5.1 is out with this solved. Check the readme for the new way to import the component. Huge thanks to @linktohack for the PR!
