### ISSUE TITLE
this is great!

### ISSUE THREAD

**Issue by superstarmcawesome** [mezoistvan/ng2-flatpickr#2]
Hey there! Really nice! love it. 
Is it possible to add weeks?
Maybe also to have a timepicker included?
And maybe have a date-range-picker?

thanks!

**Comment by mezoistvan** [comment]
Hi! Cool, I'm happy to hear that. :)

Weeks can be shown with `weekNumber: true` in the `config` input. Timepicker and date-range picker can be configured in the same way, with: `enableTime: true`, and `mode: 'range'`.

Check out https://chmln.github.io/flatpickr/options/ for all the options. Flatpickr is really flexible and this FlatpickrOptions object allows you to configure flatpickr in fine details.

I will provide examples to the ng2-flatpickr-examples page soon.

**Comment by mezoistvan** [comment]
There is a new repo for the implementation of the examples. [https://github.com/mezoistvan/ng2-flatpickr-examples-dev](https://github.com/mezoistvan/ng2-flatpickr-examples-dev) They are not linked yet, but soon will be. Check out the configuration there!
