### ISSUE TITLE
Syntax Error in IE11 and below.

### ISSUE THREAD

**Issue by chuloon** [mezoistvan/ng2-flatpickr#21]
Hello,

I'm getting a syntax error on your plugin in IE11 in both my app and your examples, and can reproduce across multiple machines. Is this a known issue? If so, is there a hotfix either you or I can do to make it work?

**Comment by mezoistvan** [comment]
Hi! 
The examples does not have the ES6 polyfills for IE11, that's for sure.
If your project works fine without this component, then a fix would be very much appreciated.

**Comment by chuloon** [comment]
I tried adding the ES6 polyfills by Babel and it didn't do the trick. Do you have suggestions on a specific polyfill that will work?

**Comment by mezoistvan** [comment]
Creating a new project with the cli will generate polyfills that just need to be uncommented. Have you tried those? Here they are in the examples repo: https://github.com/mezoistvan/ng2-flatpickr-examples/blob/master/src/polyfills.ts

**Comment by chuloon** [comment]
Yeah, all of them are uncommented from other plug-ins we're using.

**Comment by mezoistvan** [comment]
:( You can work on this if you'd like, I don't think I'll have the time in the near future

**Comment by mezoistvan** [comment]
version 0.4.0 is out. It uses flatpickr v4.0.6, and has this issue fixed!
