### ISSUE TITLE
Open the calendar by clicking another html element

### ISSUE THREAD

**Issue by LordAlastair** [mezoistvan/ng2-flatpickr#25]
Is there a way to call the flatpickr calendar by clicking a button and insert the selected date into another input field? Something like:
![image](https://user-images.githubusercontent.com/6444470/32112920-69e75330-bb1d-11e7-8587-4af3494d554b.png)

I tried the code below but without success:
```
<div class="input-group">
     <span class="input-group-btn">
         <button type="button" class="btn btn-primary btn-icon" (click)="d.toggle()">
              <i class="ion-android-calendar"></i>
         </button>
     </span>
    <input class="form-control " placeholder="Data de Nascimento" name="nascimento"
         ng2-flatpickr  #d="ng2-flatpickr" formControlName="nascimento"
         (focus)="d.open()" (click)="d.open()">
</div>
```

**Comment by cpru2** [comment]
I second this — I've tried the above — I've also tried using the wrap option to extend my framework, but this seems to overwrite both flatpickr's built-in styles and options.

**Comment by mezoistvan** [comment]
I am not exactly sure what you're trying to accomplish here: to have a datepicker field and have a separate button that opens the calendar in the datepicker field?

**Comment by LordAlastair** [comment]
Unfortunately the flatpickr breaks the application's UI and the client did not like it ☹
I tried to override the flatpickr tags, but without success = /

**Comment by cpru2** [comment]
@LordAlastair flatpickr seems to be grabbing styles from the default DOM input selector. You could change this in your project's css or scss file, or in the flatpickr stylesheet itself, but this only works about 50% of the time. The other 50% it will break the application's UI. Also not best practice and annoying if you intend on using inputs anywhere else in your project.

**Comment by GonzaloChacon** [comment]
Hey guys, I've solved this like so: 

1st - Create a template variable

     <ng2-flatpickr
       [config]="datepickerOptions"
       #datepicker>
     </ng2-flatpickr>

     <a (click)="toggle()">Something</a>


2nd - Implement ViewChild in controller to access #datepicker instance, you can access to "flatpickr" and its methods, including toggle, open, etc...

<pre>
<code>
import { Component, ViewChild } from '@angular/core'

@Component({
  selector: 'some-component',
  templateUrl: './some.component.html'
})
export class SomeComponent {
  @ViewChild('datepicker') datepicker`

  toggle(): void {
    this.datepicker.flatpickr.toggle()
  }
}
</code>
</pre>

...so far seems to work.

**Comment by mrsaravanan** [comment]
I am trying to open/close calendar from external trigger. i tried to follow same approach give by  GonzaloChacon but not seeing methods like open, close or toggle to access .. 

line "this.datepicker.flatpickr.toggle();" throws compilation error as " property toggle does not exists on object"..
