### ISSUE TITLE
two copies of ng2-flatpickr on one template

### ISSUE THREAD

**Issue by Arpanx** [mezoistvan/ng2-flatpickr#27]
Here is a code when the component is first displayed, thinks for a long time, pours errors into the console. Then in 3-5 seconds there are calendars.
when [setDate] = "xxxx" in one instance, then everything is fine.
In two copies of the delay and error
I write so thoughts in the ear
```
<td>
    <div class="divTableCell">
        <ng2-flatpickr  [setDate]="DateStart" [config]="exampleOptions" (change)="onChangeDateStart($event)"></ng2-flatpickr>
    </div>
</td>
<td>
    <div class="divTableCell">
        <ng2-flatpickr  [setDate]="DateEnd"  [config]="exampleOptions" (change)="onChangeDatePickerEnd($event)"></ng2-flatpickr>
    </div>
</td>
```
 ngOnInit() {
        this.DateStart = new Date(this.item.timeStart.substr(0, 10));
        this.DateEnd = new Date(this.item.timeEnd.substr(0, 10));
    }

**Comment by mezoistvan** [comment]
Please post a reproduction and I'll take a look.
