### ISSUE TITLE
inline mode

### ISSUE THREAD

**Issue by Nik1990** [mezoistvan/ng2-flatpickr#29]
It is possible to use inline mode?
I tried but seem to receive an error:

`Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

Thanks

**Comment by brejw** [comment]
Hello,
I had same problem but i managed to solve it.
I found explanation for this problem on StackOverflow https://stackoverflow.com/questions/9128015/getting-cannot-read-property-nodetype-of-null-when-calling-ko-applybindings 

Then I applied config in ngOnInit, where you have to bind our calendar do HTMLElement
`this.pickerConfig = {
      ...
      appendTo: document.getElementById('ID'),
      inline: true,
     ...
}`

After this calendar shows on the page in inline mode :)

**Comment by Nik1990** [comment]
Ok it works :dagger: 

Thanks
