### ISSUE TITLE
systemjs

### ISSUE THREAD

**Issue by bonaparte89** [mezoistvan/ng2-flatpickr#3]
hey there. 
I had an issue getting it to work with system js. I had to change the import in ng2-flatpicker.component.js 
import * as flatpickr from 'flatpickr/dist/flatpickr';
//require('flatpickr');

it would also be great to have a module which you can import and not declare it in ngmodules. 
if you need any help let me know 👍

**Comment by mezoistvan** [comment]
Hi! I haven't tried it with system.js yet, but will investigate later this week. Feel free to create a PR though!

**Comment by niravpatel9898** [comment]
Having a system.js here would be very helpful.

**Comment by mezoistvan** [comment]
I am not working on this issue, but I'd merge a fix in a heartbeat! :)
