### ISSUE TITLE
Weekdays aren't being styled properly

### ISSUE THREAD

**Issue by KolbySisk** [mezoistvan/ng2-flatpickr#34]
#I followed the README to get started, everything is default.

`<ng2-flatpickr></ng2-flatpickr>
`

I think the problem is caused by an unexpected container: `.flatpickr-weekdaycontainer`

The problem is fixed by adding styles to that container class:
  ```
  display: flex;
  width: 100%;
```

![screen shot 2018-04-05 at 1 58 52 pm](https://user-images.githubusercontent.com/1395078/38383168-c10ee954-38d9-11e8-9788-051d6dad1635.png)

Here's what the relevant html structure looks like:

```
<div class="flatpickr-innerContainer">
    <div class="flatpickr-rContainer">
        <div class="flatpickr-weekdays">
            <div class="flatpickr-weekdaycontainer">
                <span class="flatpickr-weekday">Sun</span>
                <span class="flatpickr-weekday">Mon</span>
                <span class="flatpickr-weekday">Tue</span>
                <span class="flatpickr-weekday">Wed</span>
                <span class="flatpickr-weekday">Thu</span>
                <span class="flatpickr-weekday">Fri</span>
                <span class="flatpickr-weekday">Sat</span>
            </div>
        </div>
    </div>
</div>
```

**Comment by mezoistvan** [comment]
This is very interesting, as this wrapper should not modify the original flatpickr in any way. So far I haven't seen anything like this. Could you please post a reproduction so I can take a look?
