### ISSUE TITLE
Set a date programmatically

### ISSUE THREAD

**Issue by rafaelgoulart** [mezoistvan/ng2-flatpickr#4]
Hi! Nice work here!

One question: how do I programmatically set a date to update the input value?

Thank you

**Comment by mezoistvan** [comment]
Hi, thanks! 👍 Initially I thought that it can be done using the FlatpickrOptions, but that is not the case unfortunately. I'll look into it later this week.

**Comment by mezoistvan** [comment]
v0.1.13 now has this functionality. check out the [readme ](https://github.com/mezoistvan/ng2-flatpickr/blob/master/README.md)and the [examples](https://mezoistvan.github.io/ng2-flatpickr-examples/)

**Comment by jomy-joseph** [comment]
how to clear date field once form submited?

**Comment by kgupta1988** [comment]
Getting Error
`LookupReservationComponent.html:1 ERROR TypeError: Cannot read property 'setDate' of undefined
    at Ng2FlatpickrComponent.setDateFromInput (ng2-flatpickr.component.js?7662:39)
    at Ng2FlatpickrComponent.ngOnChanges (ng2-flatpickr.component.js?7662:52)
    at checkAndUpdateDirectiveInline (core.js?223c:12092)
    at checkAndUpdateNodeInline (core.js?223c:13598)
    at checkAndUpdateNode (core.js?223c:13541)
    at debugCheckAndUpdateNode (core.js?223c:14413)
    at debugCheckDirectivesFn (core.js?223c:14354)
    at Object.View_LookupReservationComponent_0._co [as updateDirectives] (LookupReservationComponent.html:1)
    at Object.debugUpdateDirectives [as updateDir`

**Comment by kgupta1988** [comment]
Here _flatpickr is undefined.
`setDateFromInput( date: any ) {
		this.flatpickrElement.nativeElement._flatpickr.setDate( date, true );
	}`

**Comment by manar-mk** [comment]
@kgupta1988 Hi. Did you solve that error?

**Comment by kgupta1988** [comment]
@manar-mk I used something like this
`dateOptions: FlatpickrOptions = {
    defaultDate: '',
    allowInput: true,
    dateFormat: 'm-d-y'
  };
this.dateOptions.defaultDate = formVal.arrDate
`

**Comment by IbrahimAyed1** [comment]
The same issue is still there because I'm facing it now and even using setDate reveals another issue in the console ( ExpressionChangedAfterItHasBeenCheckedError ), I wish they fix it
