### ISSUE TITLE
Handling flatpickr hooks

### ISSUE THREAD

**Issue by KolbySisk** [mezoistvan/ng2-flatpickr#44]
Flatpickr documentation has a [page with hooks](https://flatpickr.js.org/events/#hooks)

In their example you can use onChange to get `selectedDates, dateStr, instance`

```
onChange: function(selectedDates, dateStr, instance) {
        //...
},
```

Is there a way to use these hooks? A way I can access `selectedDates, dateStr, instance`? Or should just rely on `input.value`?

Thanks

**Comment by KolbySisk** [comment]
Figured out that you can pass an onChange function in the config object. Maybe a section could be added to the documentation dedicated to getting the selected values.

**Comment by rdelriods01** [comment]
Hi @KolbySisk could you explain how did you use the onChange function please? How can I set the `selectedDates` or the `dateStr` to a variable in my Component?

**Comment by KolbySisk** [comment]
@rdelriods01 Just add a function to your config.

```
datePickerConfig = {
    onChange: (selectedDates, dateStr, instance) => {
      console.log(selectedDates);
    }
};
```
