### ISSUE TITLE
locale to the options

### ISSUE THREAD

**Issue by grubby14** [mezoistvan/ng2-flatpickr#49]
use locale options :
import Mandarin from 'flatpickr/dist/l10n/zh.js';
dateTimeOptions: FlatpickrOptions = {
        enableTime: true,
        locale: Mandarin.zh,
        onChange: (e) => {
            
        }
    }
ng build error: 
ERROR in node_modules/flatpickr/dist/l10n/zh.d.ts(58,20): error TS1005: ';' expected.
node_modules/flatpickr/dist/l10n/zh.d.ts(58,21): error TS1003: Identifier expected.
node_modules/flatpickr/dist/l10n/zh.d.ts(58,39): error TS1005: ';' expected.

**Comment by mezoistvan** [comment]
Please provide a more detailed reproduction of the issue. Closing until then.
