### ISSUE TITLE
formControlName not working

### ISSUE THREAD

**Issue by pjhartin** [mezoistvan/ng2-flatpickr#5]
Firstly, thank you for porting flatpickr to ng2. 

Today, we tried to hookup the `ng2-flatpickr` component using the following sytnax:

`<ng2-flatpickr formControlName="campaign_end_date"></ng2-flatpickr>`

I know 100% that our formControlName is initialised and setup correctly, due to testing with other components, but no matter what I try, I cannot seem to get the value out of the flatpickr component. 

Am I missing something obvious? Your help would be greatly appreciated. Running `"ng2-flatpickr": "^0.1.8"` btw.

**Comment by mezoistvan** [comment]
Hi! 
In my opinion, that should be enough. Are there any error messages? Could you please share more of your component?

**Comment by rob-balfre** [comment]
Yeah, I've got the same issues as @pjhartin. No errors, just can't access the value. I'm following this guide on the official docs for creating dynamic forms, all my other field types are working and return their values. https://angular.io/docs/ts/latest/cookbook/dynamic-form.html

Do you have some source code for a working example?

**Comment by mezoistvan** [comment]
Indeed there was a bug in 0.1.8. It is fixed in 0.1.9, and there is a working example at [https://mezoistvan.github.io/ng2-flatpickr-examples/](https://mezoistvan.github.io/ng2-flatpickr-examples/).

**Comment by mezoistvan** [comment]
Oops, didnt mean to close it. If its working fine, I'll close it for real in a few days. 

There is a new repo for the development of the examples, if you are interested in the actual implementation. [https://github.com/mezoistvan/ng2-flatpickr-examples-dev](https://github.com/mezoistvan/ng2-flatpickr-examples-dev)

**Comment by rob-balfre** [comment]
Thanks @mezoistvan.  I hadn't built my own form component wrapper yet so dived in a built one myself, seems to be working well. Source code looks similar to yours.  Heres the gist... https://gist.github.com/rob-balfre/d1ef9e92a262e5816737ae64b5bbe868

**Comment by mezoistvan** [comment]
Yep, looks good! The line `onChange: (date) => this.propagateChange(date[0] || '')` makes it unusable for date-range picking as far as I know. But providing the date itself and not the whole array is a good idea!

**Comment by mezoistvan** [comment]
I finally moved the examples -dev  to its right place https://github.com/mezoistvan/ng2-flatpickr-examples You can find the examples there. Closing this for now.

**Comment by pjhartin** [comment]
Thanks @mezoistvan !
