### ISSUE TITLE
Error: Cannot find module 'ng2-flatpickr'

### ISSUE THREAD

**Issue by dockleryxk** [mezoistvan/ng2-flatpickr#63]
On Angular 6 with AOT I get this error. I wish I could provide more details but I don't really know what is happening. The package is definitely installed! Reverting to 7.0.3 solves it for now.

**Comment by jayvdb** [comment]
I have the same error, and also got it working by reverting to 7.0.3.

**Comment by mezoistvan** [comment]
Oops! Just published v7.0.5, which should be ok. Sorry, it was definitely an error on my side.
