### ISSUE TITLE
debug.log should not be committed

### ISSUE THREAD

**Issue by eddiejaoude** [mezoistvan/ng2-flatpickr#64]
Add to `.gitignore`

```
*.log
```

**Comment by mezoistvan** [comment]
This is a good catch though, added, thanks! 👍

**Comment by eddiejaoude** [comment]
cool 👍 . We were reviewing your project as part of our youtube live stream and someone contributes plus uses your project, wanted to contribute more and was looking for suggestions 🤓 ... here is the live stream https://www.youtube.com/watch?v=Aa5se-WebiE

**Comment by mezoistvan** [comment]
Hehe nice! 👍 Neat idea, hope it catches on!

**Comment by eddiejaoude** [comment]
Thank you 🤓
