### ISSUE TITLE
build:ssr

### ISSUE THREAD

**Issue by Ramon2000** [mezoistvan/ng2-flatpickr#67]
I build my code with:
`npm run build:ssr`

run the server:
`node dist/server.js`

and get the following error
```
 node dist/server.js
/angular-client/dist/server.js:160615
        Object(tslib__WEBPACK_IMPORTED_MODULE_0__["__metadata"])("design:type", HTMLElement)
                                                                                ^
ReferenceError: HTMLElement is not defined
    at /angular-client/dist/server.js:160615:81
at Module.<anonymous> (/.../angular-client/dist/server.js:160747:2)
    at __webpack_require__ (/.../angular-client/dist/server.js:20:30)
    at Object.ng2-flatpickr (/.../angular-client/dist/server.js:63977:18)
```

As you can see, it links to ng2-flatpickr

My related files in package.json:
```
"dependencies": {
    "@angular/common": "^7.1.0",
    "@angular/compiler": "^7.1.0",
    "@angular/core": "^7.1.0",
    "core-js": "^2.5.4",
    "flatpickr": "^4.6.1",
    "ng2-flatpickr": "^8.0.1",
    "rxjs": "^6.5.1",
    "rxjs-compat": "^6.5.1",
  },
```

Anyone else having the same issue? After doing some research earlier, I more or less ended up here: https://angular.io/api/core/Renderer2#description

For serverside rendering, it seems you need to use renderer2 and inject a document like this:
```
import { DOCUMENT } from '@angular/common';
import { Component, Inject, Renderer2 } from '@angular/core';
constructor(@Inject(DOCUMENT) document, r: Renderer2) {
    r.addClass(document.body, 'myclass');
 }
```

You already looked at Serverside rendering?

**Comment by Ramon2000** [comment]
Upgraded to Angular8 and issue still exist.
Also checked, and saw you are already making use of renderer2
https://github.com/mezoistvan/ng2-flatpickr/blob/master/dist/src/ng2-flatpickr.directive.d.ts#L11

**Comment by mezoistvan** [comment]
I will look into this this week. Flatpickr might try to access the document directly when it loads, but I'll make sure the ssr build does not fail.

**Comment by dockleryxk** [comment]
@mezoistvan it looks like the problem is that type HTMLElement doesn't exist on the server.

Even Angular types ElementRef.nativeElement as any instead of HTMLElement. I'll make a PR for this

**Comment by dockleryxk** [comment]
@mezoistvan it looks like the problem is that type HTMLElement doesn't exist on the server.

Even Angular types ElementRef.nativeElement as any instead of HTMLElement. I'm not sure how this ever worked with server side rendering though, considering it's been using that typing quite a bit for a a while now.

**Comment by Ramon2000** [comment]
The build itself actually passes, it's when you try to run 
` node dist/server.js`

**Comment by m-abuseini** [comment]
is there any update on this issue?
