### ISSUE TITLE
ERROR TypeError: "this.flatpickrElement is undefined" in ngOnChanges

### ISSUE THREAD

**Issue by SaschaSchwarze0** [mezoistvan/ng2-flatpickr#68]
I am building an application that is based on Angular 8 and carbon-components-angular. Its DatePicker component (https://github.com/IBM/carbon-components-angular/blob/master/src/datepicker/datepicker.component.ts) uses ng2-flatpickr (at version 8.0.1). I am seeing the following error:

ERROR TypeError: "this.flatpickrElement is undefined"
    ngOnChanges ng2-flatpickr.js:50

The reason in my opinion is an incorrectly set static flag of the flatpickrElement view child in https://github.com/mezoistvan/ng2-flatpickr/blob/master/src/ng2-flatpickr.component.ts#L39.

Given the child is not inside an ngIf and ngFor, it is static. Setting it to static=true resolves the issue for me.

**Comment by ribbskott** [comment]
@SaschaSchwarze0 i forked the repo and tried your solution, i was experiencing the same thing and can confirm that setting the ViewChild static flag to true fixed it.

**Comment by Ramon2000** [comment]
Hello, 

Any chance there is an ETA? I prefer not to fork if it gets updated soon.

Cheers

**Comment by chaouiy** [comment]
same probleme here

**Comment by chaouiy** [comment]
someone merge the pull request, it is just about turning false to true

**Comment by agroves333** [comment]
Bump

**Comment by kamihamiha123** [comment]
@ribbskott how can one use your fork until pull request approval. it show` Cannot find module 'ng2-flatpickr'` it must be about build that is missing ?

**Comment by mezoistvan** [comment]
I apologize for the long wait, I was away and anywhere in the past weeks. Merged and released in v8.0.2
