### ISSUE TITLE
cannot read property nativeElement of undefined after updating to ng2-flatpickr 8.0.1and angular to 8

### ISSUE THREAD

**Issue by chaouiy** [mezoistvan/ng2-flatpickr#71]
Error : 
`EDatepickerComponent.html:1 ERROR TypeError: Cannot read property 'nativeElement' of undefined     at Ng2FlatpickrComponent.push../node_modules/ng2-flatpickr/fesm5/ng2-flatpickr.js.Ng2FlatpickrComponent.ngOnChanges (ng2-flatpickr.js:55)     at checkAndUpdateDirectiveInline (core.js:19337)     at checkAndUpdateNodeInline (core.js:27597)     at checkAndUpdateNode (core.js:27559)     at debugCheckAndUpdateNode (core.js:28193)     at debugCheckDirectivesFn (core.js:28153)     at Object.eval [as updateDirectives] (EDatepickerComponent.html:1)     at Object.debugUpdateDirectives [as updateDirectives] (core.js:28145)     at checkAndUpdateView (core.js:27541)     at callViewAction (core.js:27782)`

Version:
```
 "ng2-flatpickr": {
      "version": "8.0.1",
      "resolved": "https://registry.npmjs.org/ng2-flatpickr/-/ng2-flatpickr-8.0.1.tgz",
      "integrity": "sha512-kLjEDjeyRzth7NZ1gX/pygOTuMDx+8Xj/Ur5CcQdBfnZ0cWFW6jORTDy1Tx/6C/vcMsrroBznbBYzpcsGNrfyQ==",
      "requires": {
        "tslib": "^1.9.0"
      }
    },
```

**Comment by langebangen** [comment]
I have the same issue

**Comment by AlexAegis** [comment]
Same issue

**Comment by kamihamiha123** [comment]
same issue

**Comment by mezoistvan** [comment]
Is this still an issue? I haven't encountered it with v8.0.4 released today.
