### ISSUE TITLE
Need help getting a Date object with formControl

### ISSUE THREAD

**Issue by david-dasilva** [mezoistvan/ng2-flatpickr#80]
Hi,

I have the same question as #22 : how to get a Date object, or the formated date string of the datepicker?

So far I have
```
<form [formGroup]="userConf">
<ng2-flatpickr type="date"  id="endValidity" formControlName="endValidity" [config]="datepickerOptions" required></ng2-flatpickr>
</form>
```

and
```
datepickerOptions: FlatpickrOptions = {
    locale: French.fr,
    altInput: true,
    altFormat: 'j/m/Y',
    dateFormat: 'Y-m-d',
    allowInput: true
  };

userConf = this.fb.group({
    ...
    endValidity: ['', Validators.required],
    ...
  }, {validators: DateOrderValidator('startValidity', 'endValidity')});
```

but when I try to get the value with `this.userConf.get('endValidity').value` I get `[Wed Feb 12 2020 00:00:00 GMT+0100 (heure normale d’Europe centrale)]` where I would expect a Date objet or the string '2020-02-15' as specified in the dateFormat option.

Am I missing something? Thx for the awesome work!

**Comment by david-dasilva** [comment]
Wait a minute. It seems I do have a date Object, but inside an array. 
I've been fooled by the DevTools showing the ISO string of the Date object.
Why such array? Is it part of how flatpickr works?
In order to retrieve my Date object I have to do `this.userConf.get('endValidity').value[0]` which seems weird

**Comment by mezoistvan** [comment]
That is part of how flatpickr works, as it provides the selected dates in an array. The `Ng2FlatpickrComponent` just pushes that value to the form using the `onChange` property of `FlatpickrOptions`. See: https://github.com/mezoistvan/ng2-flatpickr/blob/master/src/ng2-flatpickr.component.ts#L36

You can overwrite this by setting your custom `onChange` property in `FlatpickrOptions`. Something like this: https://stackblitz.com/edit/ng2-flatpickr-custom-onchange would work.

**Comment by david-dasilva** [comment]
Thanks @mezoistvan for the input.
I knew I was missing something here :)
